### ISSUE TITLE
Add Gnome 45 Support

### ISSUE THREAD

**Issue by sandenbergmelo** [Tommimon/super-key#2]
Add support for Gnome 45

**Comment by javiersc1** [comment]
#3 

Submitted a pull request for this. If you need this working now, simply edit the 3 files per my commit to your .local/share/gnome-shell/extensions/superkey directory....

**Comment by X07U** [comment]
@javiersc1 my lord and savior. I got so used to binding Ulauncher to super key that I could not imagine doing it another way. Thank you so much.

**Comment by Tommimon** [comment]
@javiersc1 thanks for the help. In the last weeks I didn't find the time to update the extension myself. [A new release](https://github.com/Tommimon/super-key/releases/tag/v5) for GNOME 45 is available and I submitted it for review on [GNOME extensions website](https://extensions.gnome.org/extension/5188/super-key/).
